services:
  backend:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - PROJECT_ROOT=/project
    volumes:
      - ./app:/app
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ../ai:/project/ai:ro
