"""initial

Revision ID: f578c369e907
Revises: 
Create Date: 2026-06-19 01:37:49.460627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f578c369e907'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=False),
    sa.Column('exercise_video_url', sa.String(length=500), nullable=True),
    sa.Column('reference_motion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('exercise_name')
    )
    op.create_table('doctor_notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('notification_content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('운동미수행', '운동차단')", name='ck_doctor_notification_type'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=True),
    sa.Column('surgery_name', sa.String(length=100), nullable=True),
    sa.Column('surgery_area', sa.String(length=50), nullable=True),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('rehab_start_date', sa.Date(), nullable=True),
    sa.Column('current_rehab_phase', sa.String(length=20), nullable=True),
    sa.Column('guardian_email', sa.String(length=100), nullable=True),
    sa.Column('report_consent', sa.Boolean(), nullable=False),
    sa.Column('ai_difficulty_enabled', sa.Boolean(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_rehab_phase IN ('초기', '중기', '후기')", name='ck_patient_phase'),
    sa.CheckConstraint("gender IN ('남', '여')", name='ck_patient_gender'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('patient_code')
    )
    op.create_table('llm_report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('guardian_sent_status', sa.String(length=20), nullable=False),
    sa.Column('exercise_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('대기', '수정', '승인')", name='ck_llm_report_approval'),
    sa.CheckConstraint("guardian_sent_status IN ('대기', '완료')", name='ck_llm_report_guardian'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('patient_id', 'report_date')
    )
    op.create_table('prescription',
    sa.Column('prescription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('rehab_phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rehab_phase IN ('초기', '중기', '후기')", name='ck_prescription_phase'),
    sa.CheckConstraint("status IN ('대기', '적용중', '종료')", name='ck_prescription_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('social_account',
    sa.Column('social_account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('social_platform', sa.String(length=100), nullable=False),
    sa.Column('social_user_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("social_platform IN ('google', 'kakao', 'naver')", name='ck_social_platform'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('social_account_id'),
    sa.UniqueConstraint('social_platform', 'social_user_id')
    )
    op.create_table('prescription_exercise',
    sa.Column('prescription_exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.prescription_id'], ),
    sa.PrimaryKeyConstraint('prescription_exercise_id'),
    sa.UniqueConstraint('prescription_id', 'exercise_order')
    )
    op.create_table('exercise_schedule',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_exercise_id'], ['prescription_exercise.prescription_exercise_id'], ),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('prescription_exercise_id', 'exercise_date')
    )
    op.create_table('prescription_finger_setting',
    sa.Column('finger_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_exercise_id', sa.Integer(), nullable=False),
    sa.Column('hand_type', sa.String(length=10), nullable=False),
    sa.Column('finger_type', sa.String(length=10), nullable=False),
    sa.Column('target_rom', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("finger_type IN ('엄지', '검지', '중지', '약지', '소지')", name='ck_finger_setting_finger'),
    sa.CheckConstraint("hand_type IN ('왼손', '오른손')", name='ck_finger_setting_hand'),
    sa.ForeignKeyConstraint(['prescription_exercise_id'], ['prescription_exercise.prescription_exercise_id'], ),
    sa.PrimaryKeyConstraint('finger_setting_id'),
    sa.UniqueConstraint('prescription_exercise_id', 'hand_type', 'finger_type')
    )
    op.create_table('rehab_exercise_session',
    sa.Column('rehab_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['exercise_schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('rehab_session_id')
    )
    op.create_table('rehab_exercise_capture',
    sa.Column('capture_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rehab_session_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_first_photo_url', sa.String(length=500), nullable=True),
    sa.Column('set_last_photo_url', sa.String(length=500), nullable=True),
    sa.Column('overload_before_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rehab_session_id'], ['rehab_exercise_session.rehab_session_id'], ),
    sa.PrimaryKeyConstraint('capture_id'),
    sa.UniqueConstraint('rehab_session_id', 'set_number')
    )
    op.create_table('rehab_exercise_log',
    sa.Column('rehab_exercise_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rehab_session_id', sa.Integer(), nullable=False),
    sa.Column('performed_reps', sa.Integer(), nullable=True),
    sa.Column('performed_sets', sa.Integer(), nullable=True),
    sa.Column('progress_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("end_type IN ('완료', '목표조정', '안전종료', '운동차단')", name='ck_rehab_log_end_type'),
    sa.ForeignKeyConstraint(['rehab_session_id'], ['rehab_exercise_session.rehab_session_id'], ),
    sa.PrimaryKeyConstraint('rehab_exercise_log_id')
    )
    op.create_table('finger_accuracy',
    sa.Column('finger_accuracy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rehab_exercise_log_id', sa.Integer(), nullable=False),
    sa.Column('hand_type', sa.String(length=10), nullable=False),
    sa.Column('finger_type', sa.String(length=10), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rom', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("finger_type IN ('엄지', '검지', '중지', '약지', '소지')", name='ck_finger_accuracy_finger'),
    sa.CheckConstraint("hand_type IN ('왼손', '오른손')", name='ck_finger_accuracy_hand'),
    sa.ForeignKeyConstraint(['rehab_exercise_log_id'], ['rehab_exercise_log.rehab_exercise_log_id'], ),
    sa.PrimaryKeyConstraint('finger_accuracy_id'),
    sa.UniqueConstraint('rehab_exercise_log_id', 'hand_type', 'finger_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finger_accuracy')
    op.drop_table('rehab_exercise_log')
    op.drop_table('rehab_exercise_capture')
    op.drop_table('rehab_exercise_session')
    op.drop_table('prescription_finger_setting')
    op.drop_table('exercise_schedule')
    op.drop_table('prescription_exercise')
    op.drop_table('social_account')
    op.drop_table('prescription')
    op.drop_table('llm_report')
    op.drop_table('patient')
    op.drop_table('doctor_notification')
    op.drop_table('exercise')
    op.drop_table('doctor')
    # ### end Alembic commands ###
