/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#004444',
        'on-primary': '#ffffff',
        'primary-container': '#0d5d5d',
        'on-primary-container': '#90d3d3',
        'primary-fixed': '#aaefee',
        'primary-fixed-dim': '#8fd2d2',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f50',
        'inverse-primary': '#8fd2d2',
        secondary: '#4858ab',
        'on-secondary': '#ffffff',
        'secondary-container': '#96a5ff',
        'on-secondary-container': '#27378a',
        'secondary-fixed': '#dee0ff',
        'secondary-fixed-dim': '#bac3ff',
        'on-secondary-fixed': '#00105b',
        'on-secondary-fixed-variant': '#2f3f92',
        tertiary: '#5e2f2d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#794543',
        'on-tertiary-container': '#fcb6b2',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#fbb5b1',
        'on-tertiary-fixed': '#350f0e',
        'on-tertiary-fixed-variant': '#6a3937',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9f6',
        'on-background': '#1a1c1a',
        surface: '#f9f9f6',
        'on-surface': '#1a1c1a',
        'surface-variant': '#e2e3e0',
        'on-surface-variant': '#3f4948',
        'surface-dim': '#dadad7',
        'surface-bright': '#f9f9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f1',
        'surface-container': '#eeeeeb',
        'surface-container-high': '#e8e8e5',
        'surface-container-highest': '#e2e3e0',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f1f1ee',
        outline: '#6f7978',
        'outline-variant': '#bec8c8',
        'surface-tint': '#1f6868',
        'doctor-primary': '#005bbf',
        'doctor-primary-container': '#1a73e8',
        'doctor-secondary': '#006398',
        'brand-teal': '#00A896',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        base: '4px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '40px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'Noto Sans KR', 'sans-serif'],
        sans: ['Inter', 'Noto Sans KR', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0px 4px 12px rgba(0, 0, 0, 0.05)',
        'card-hover': '0px 8px 24px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
